development:
  client_id: 571308755426.apps.googleusercontent.com
  client_secret: D9O7PKMwPCZwrOifsTwR6GC9
  redirect_uri: http://localhost:3000/oauth2callback

test:
  client_id: 571308755426.apps.googleusercontent.com
  client_secret: D9O7PKMwPCZwrOifsTwR6GC9
  redirect_uri: http://localhost:3000/oauth2callback

production:
  client_id: 571308755426-ej3mban516jph0biijoe6ji159r0gegm.apps.googleusercontent.com
  client_secret: LlD2ZFgM8pd093FzQDQ6fc16
  redirect_uri: http://still-cove-9467.herokuapp.com/oauth2callback